#define INVALID_COMMAND 100
#define WRONG_NUMBER_OF_ARGUMENTS 101
#define QUIT_SHELL 102
#define MEMORY_EXCEED 103
#define VARIABLE_DOES_NOT_EXISTS 104
#define FILE_NOT_FOUND 105
#define RAM_MEMORY_EXCEED 106
#define END_OF_FILE 106
#define PAGE_NOT_INITIALIZED 107

#define FRAMESIZE 4
